"""Initiale migrate

Revision ID: 8721c5d84072
Revises: 
Create Date: 2022-09-12 21:27:19.026807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8721c5d84072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('masquer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avis'))
    )
    op.create_table('billets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=80), nullable=True),
    sa.Column('lien_session', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billets')),
    sa.UniqueConstraint('titre', name=op.f('uq_billets_titre'))
    )
    op.create_table('categorie_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorie_article'))
    )
    op.create_table('categorie_podcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lienspotify', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorie_podcast'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=80), nullable=True),
    sa.Column('cout', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=80), nullable=True),
    sa.Column('presentiel', sa.Boolean(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('nom_de_place', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('date', name=op.f('uq_events_date')),
    sa.UniqueConstraint('titre', name=op.f('uq_events_titre'))
    )
    op.create_table('livres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=80), nullable=True),
    sa.Column('lien_achat', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_livres'))
    )
    op.create_table('reponse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reponse'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=True),
    sa.Column('prenom', sa.String(length=80), nullable=True),
    sa.Column('profession', sa.String(length=80), nullable=True),
    sa.Column('birthday', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('titre', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cat_article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_article_id'], ['categorie_article.id'], name=op.f('fk_articles_cat_article_id_categorie_article')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('titre', name=op.f('uq_articles_titre'))
    )
    op.create_table('association',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_association_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_association_user_id_users'))
    )
    op.create_table('podcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=80), nullable=True),
    sa.Column('ifram', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('cat_podcast_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_podcast_id'], ['categorie_podcast.id'], name=op.f('fk_podcasts_cat_podcast_id_categorie_podcast')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_podcasts'))
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('reponse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reponse_id'], ['reponse.id'], name=op.f('fk_question_reponse_id_reponse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('podcasts')
    op.drop_table('association')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('reponse')
    op.drop_table('livres')
    op.drop_table('events')
    op.drop_table('categorie_podcast')
    op.drop_table('categorie_article')
    op.drop_table('billets')
    op.drop_table('avis')
    # ### end Alembic commands ###
